name: Build pull request

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Setting up ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build:prod
    
    - name: Lint
      run: npm run lint

    - name: Test
      run: npm test
    
    - name: Release preview
      run: npx auto shipit --dry-run
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
