name: Publish

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN_PARAM }}

    - name: Setting up Node.js
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
        node-version: 18

    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build:prod
    
    - name: Publish
      run: |
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config user.name "$GITHUB_ACTOR"
        npx auto shipit
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
